apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-ro
  name: osm-ro
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    osm-service: osm-ro
status:
  loadBalancer: {}
---
apiVersion: v1
data:
  RO_DB_ROOT_PASSWORD: "12345678"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-ro-env
  name: osm-ro-env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-ro
  name: osm-ro
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-ro
  name: osm-ro
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-ro
    spec:
      containers:
      - env:
        - name: RO_DB_HOST
          value: osm-ro-db
        - name: RO_DB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: RO_DB_ROOT_PASSWORD
              name: osm-ro-env
        image: opensourcemano/ro:latest
        name: osm-ro
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - mountPath: /var/log/osm
          name: osm-ro
      restartPolicy: Always
      volumes:
      - name: osm-ro
        persistentVolumeClaim:
          claimName: osm-ro
status: {}
