apiVersion: v1
data:
  KEYSTONE_DB_PASSWORD: "12345678"
  NBI_PASSWORD: "12345678"
  ROOT_DB_PASSWORD: "12345678"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-keystone-keystone-env
  name: osm-keystone-keystone-env
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: keystone
  name: keystone
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    osm-service: osm-keystone
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-keystone
  name: osm-keystone
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-keystone
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: osm-keystone-db
        - name: KEYSTONE_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: KEYSTONE_DB_PASSWORD
              name: osm-keystone-keystone-env
        - name: NBI_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NBI_PASSWORD
              name: osm-keystone-keystone-env
        - name: ROOT_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: ROOT_DB_PASSWORD
              name: osm-keystone-keystone-env
        image: opensourcemano/keystone:latest
        name: osm-keystone
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
