apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-prometheus-configmap
  name: osm-prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['osm-mon:8000']
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-prometheus-data
  name: osm-prometheus-data
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-prometheus
  name: osm-prometheus
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    osm-service: osm-prometheus
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-prometheus
  name: osm-prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-prometheus
    spec:
      containers:
      - image: prom/prometheus:latest
        name: osm-prometheus
        ports:
        - containerPort: 9090
        resources: {}
        args:
          - --config.file=/etc/config/prometheus.yml
          - --storage.tsdb.path=/prometheus
          - --web.console.libraries=/etc/prometheus/console_libraries
          - --web.console.templates=/etc/prometheus/consoles
          - --web.enable-lifecycle
        volumeMounts:
        - mountPath: /etc/config/
          name: osm-prometheus-configmap
        - mountPath: /prometheus
          name: osm-prometheus-data
      hostname: osm-prometheus
      restartPolicy: Always
      volumes:
      - name: osm-prometheus-configmap
        configMap:
          name: osm-prometheus-configmap
      - name: osm-prometheus-data
        persistentVolumeClaim:
          claimName: osm-prometheus-data
      securityContext:
        runAsUser: 0
status: {}
