apiVersion: v1
data:
  OSMLCM_VCA_HOST: localhost
  OSMLCM_VCA_SECRET: "12345678"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-lcm-env
  name: osm-lcm-env
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-lcm
  name: osm-lcm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-lcm
    spec:
      containers:
      - env:
        - name: OSMLCM_DATABASE_URI
          value: mongodb://osm-mongo:27017
        - name: OSMLCM_MESSAGE_HOST
          value: osm-kafka
        - name: OSMLCM_RO_HOST
          value: osm-ro
        - name: OSMLCM_VCA_HOST
          valueFrom:
            configMapKeyRef:
              key: OSMLCM_VCA_HOST
              name: osm-lcm-env
        - name: OSMLCM_VCA_SECRET
          valueFrom:
            configMapKeyRef:
              key: OSMLCM_VCA_SECRET
              name: osm-lcm-env
        image: opensourcemano/lcm:latest
        name: osm-lcm
        resources: {}
        volumeMounts:
        - mountPath: /app/storage
          name: osm-packages
      restartPolicy: Always
      volumes:
      - name: osm-packages
        persistentVolumeClaim:
          claimName: osm-packages
status: {}
