apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-pol-db
  name: osm-pol-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-pol
  name: osm-pol
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-pol
    spec:
      containers:
      - env:
        - name: OSMPOL_MESSAGE_HOST
          value: osm-kafka
        - name: OSMPOL_DATABASE_URI
          value: mongodb://osm-mongo:27017
        - name: OSMPOL_SQL_DATABASE_URI
          value: sqlite:///app/database/policy_module.db
        image: opensourcemano/pol:latest
        name: osm-pol
        resources: {}
        volumeMounts:
        - mountPath: /app/database
          name: osm-pol-db
      restartPolicy: Always
      volumes:
      - name: osm-pol-db
        persistentVolumeClaim:
          claimName: osm-pol-db
status: {}
